apiVersion: skaffold/v2beta12
kind: Config
build: 
  local:
    push: false
  artifacts:
    - image: some_image
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml:

